spring:
  #微服务名称
  application:
    name: item-service
  #nacos注册中心
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yml
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
